name: Build and Deploy Node.js App to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install
      working-directory: ./node-url-shortener

    - name: Build project
      run: npm run build
      working-directory: ./node-url-shortener

    - name: Create ZIP package
      run: |
        cd node-url-shortener
        zip -r app.zip .
        mv app.zip ${{ github.workspace }}/app.zip

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-package
        path: app.zip

  deploy:
    name: Deploy to Azure
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download ZIP artifact
      uses: actions/download-artifact@v4
      with:
        name: app-package
        path: .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ZIP to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Surls'
        slot-name: 'production'
        package: 'app.zip'
