name: Build and Deploy Node.js App to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    outputs:
      zip-path: ${{ steps.package.outputs.zip-path }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install
      working-directory: ./node-url-shortener

    - name: Build project
      run: npm run build
      working-directory: ./node-url-shortener

    - name: Create ZIP package
      id: package
      run: |
        cd node-url-shortener
        zip -r ../app.zip .
        echo "zip-path=$(pwd)/../app.zip" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Azure
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy ZIP to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Surls'
        slot-name: 'production'
        package: '${{ needs.build.outputs.zip-path }}'
        azure-rm-credentials: ${{ secrets.AZURE_CREDENTIALS }}
