name: Deploy Node.js app to Azure Web App - surl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Instalar dependências (Necessário para rodar o 'build' e 'prisma')
      - name: Install dependencies
        working-directory: ./node-url-shortener
        run: npm install

      # 4️⃣ 🛠️ COMPILAR O TYPESCRIPT
      - name: Build TypeScript code
        working-directory: ./node-url-shortener
        run: npm run build

      # 5️⃣ Executar Migrações do Prisma (Opcional, mas crucial se você usa DB)
      # Nota: A variável DATABASE_URL deve estar configurada no Azure App Service
      - name: Run Prisma Migrations
        working-directory: ./node-url-shortener
        run: npx prisma migrate deploy
        env:
          # Use o segredo do GitHub para a migração, se necessário, 
          # ou confie no DB_URL do Azure (se já estiver configurado no Azure)
          DATABASE_URL: ${{ secrets.AZUREAPPSERVICE_DATABASE_URL }}

      # 6️⃣ 📦 CRIAR O ARQUIVO ZIP
      - name: Create Deployment Package (ZIP)
        working-directory: ./node-url-shortener
        # Comando para criar o ZIP, excluindo pastas grandes/desnecessárias:
        # -r : recursivo
        # . : todos os arquivos no diretório atual
        # -x : excluir
        run: zip -r deploy.zip . -x "node_modules/*" -x ".git/*" -x "src/*" -x "*.zip"

      # 7️⃣ Login no Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A6209AD598C4946B0F8B435FF2F7584 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48BD8A498D9A4B378EFF9980053B7EA6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_68D3C7022AF845C988A52B0E62970677 }}

      # 8️⃣ Deploy para o Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'surl'
          slot-name: 'Production'
          # APONTE PARA O ARQUIVO ZIP CRIADO NA ETAPA 6
          package: ./node-url-shortener/deploy.zip