name: Build and Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Clonar o repositório
      - uses: actions/checkout@v4

      # Passo 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Passo 3: Instalar dependências e compilar TypeScript
      - name: Install and Build
        working-directory: ./node-url-shortener
        run: |
          npm install
          npm run build

      # Passo 4: Upload do build para o job de deploy
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: ./node-url-shortener

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read


    steps:
      # Passo 1: Baixar artifact do job de build
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: ./dist

      # Passo 2: Login no Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A6209AD598C4946B0F8B435FF2F7584 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48BD8A498D9A4B378EFF9980053B7EA6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_68D3C7022AF845C988A52B0E62970677 }}

      # Passo 3: Deploy para o Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'surl'            # Nome do seu Web App
          slot-name: 'Production'
          package: ./dist              # Pasta com o JS compilado
