name: Build and deploy Node.js app to Azure Web App - surl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login no Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A6209AD598C4946B0F8B435FF2F7584 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48BD8A498D9A4B378EFF9980053B7EA6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_68D3C7022AF845C988A52B0E62970677 }}

      # 3️⃣ Prepare o pacote para deploy (apenas arquivos da app)
      - name: Zip application files
        working-directory: ./node-url-shortener
        run: |
          zip -r deploy.zip * -x "node_modules/*" ".git/*" "tests/*"

      # 4️⃣ Deploy para Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'surl'
          slot-name: 'Production'
          package: ./node-url-shortener/deploy.zip
